apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  config.json: |
    {{- merge (dict "listen" ":8443" "database" "/var/lib/tunneler/tunneler.db") .Values.config | toPrettyJson | nindent 4 }}
